id = "dash"
name = "Dash"
version = "0.1.1"
schema_version = 1
description = "Dash language support for Zed - a functional language for Dagger with Hindley-Milner type inference"
authors = ["vito"]
repository = "https://github.com/vito/dash"

[grammars.dash]
repository = "https://github.com/vito/dash"
commit = "7f11f1b4ac82ac986c30065232a4684eea284de0"
path = "treesitter"
