id = "dash"
name = "Dash"
description = "Dash language support for Zed - a functional language for Dagger with Hindley-Milner type inference"
version = "0.1.0"
schema_version = 1
authors = ["Claude <noreply@anthropic.com>"]
repository = "https://github.com/vito/dash"

[language_servers.dash-language-server]
name = "Dash Language Server"
languages = ["Dash"]

[[grammar]]
name = "dash"
repository = "https://github.com/vito/dash"
path = "treesitter"
commit = "main"