id = "dash"
name = "Dash"
description = "Dash language support for Zed - a functional language for Dagger with Hindley-Milner type inference"
version = "0.1.0"
schema_version = 1
authors = ["Claude <noreply@anthropic.com>"]
repository = "https://github.com/vito/dash"

[grammars.dash]
repository = "https://github.com/vito/dash"
commit = "7c9756d826aff94d0a5e17d38f7b5c36ccb17668"
path = "treesitter"
