// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlserver

type CreateUserInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	Age   *int   `json:"age,omitempty"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Post struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Author    *User  `json:"author"`
	CreatedAt string `json:"createdAt"`
}

type PostConnection struct {
	Posts    []*Post   `json:"posts"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type Query struct {
}

type ServerInfo struct {
	Version    string `json:"version"`
	Platform   string `json:"platform"`
	Uptime     string `json:"uptime"`
	TotalUsers int    `json:"totalUsers"`
	TotalPosts int    `json:"totalPosts"`
}

type UpdateUserInput struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
	Age   *int    `json:"age,omitempty"`
}

type User struct {
	ID     string          `json:"id"`
	Name   string          `json:"name"`
	Emails []string        `json:"emails"`
	Age    *int            `json:"age,omitempty"`
	Posts  *PostConnection `json:"posts"`
}

type UserProfile struct {
	User              *User    `json:"user"`
	JoinedDate        string   `json:"joinedDate"`
	LastActivity      string   `json:"lastActivity"`
	PostCount         *int     `json:"postCount,omitempty"`
	AveragePostLength *float64 `json:"averagePostLength,omitempty"`
	Bio               *string  `json:"bio,omitempty"`
}
