// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlserver

type CreateUserInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	Age   *int   `json:"age,omitempty"`
}

type Mutation struct {
}

type Post struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Author    *User  `json:"author"`
	CreatedAt string `json:"createdAt"`
}

type Query struct {
}

type UpdateUserInput struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
	Age   *int    `json:"age,omitempty"`
}

type User struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Email string  `json:"email"`
	Age   *int    `json:"age,omitempty"`
	Posts []*Post `json:"posts"`
}
