id = "bind"
name = "Bind"
version = "0.1.1"
schema_version = 1
description = "Bind language support for Zed"
authors = ["vito"]
repository = "https://github.com/vito/bind"

[grammars.bind]
repository = "https://github.com/vito/bind"
commit = "245235b05ab64f53df127479622a7e9e9c1b56c8"
path = "treesitter"
