id = "sprout"
name = "Sprout"
version = "0.1.1"
schema_version = 1
description = "Sprout language support for Zed"
authors = ["vito"]
repository = "https://github.com/vito/sprout"

[grammars.sprout]
repository = "https://github.com/vito/sprout"
commit = "be36e86bf7d6e12acb8bae29fdfb8b7a36ad510e"
path = "treesitter"
