id = "sprout"
name = "Sprout"
version = "0.1.1"
schema_version = 1
description = "Sprout language support for Zed"
authors = ["vito"]
repository = "https://github.com/vito/sprout"

[grammars.sprout]
repository = "https://github.com/vito/sprout"
commit = "c10811489a07aa2b6196b4b67eadccf99e0370e3"
path = "treesitter"
