// Command gen-chroma-css renders the docs' syntax-highlight palettes to a
// stylesheet. Highlighting emits chroma CSS classes (see dangdocs.init), so the
// colors live here rather than inline on every token — which is what lets code
// blocks switch palettes under prefers-color-scheme.
//
// The dark palette is the default; the light palette is emitted again, scoped
// under a prefers-color-scheme:light media query, so its rules win in light
// mode via the cascade. Run from build.sh; output is a build artifact.
package main

import (
	"bytes"
	"fmt"
	"os"

	"github.com/alecthomas/chroma/v2"
	"github.com/alecthomas/chroma/v2/formatters/html"
	dangdocs "github.com/vito/dang/docs/go"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: gen-chroma-css <out.css>")
		os.Exit(1)
	}

	// WithClasses(true) makes WriteCSS emit class selectors (.chroma .k {…})
	// rather than a style map, matching the highlighted markup.
	formatter := html.New(html.WithClasses(true))

	var buf bytes.Buffer
	buf.WriteString("/* Generated by gen-chroma-css; do not edit. */\n")

	if err := formatter.WriteCSS(&buf, dangdocs.DangDarkStyle); err != nil {
		fmt.Fprintln(os.Stderr, "dark:", err)
		os.Exit(1)
	}

	buf.WriteString("@media (prefers-color-scheme:light){\n")
	if err := writeIndented(&buf, formatter, dangdocs.DangLightStyle); err != nil {
		fmt.Fprintln(os.Stderr, "light:", err)
		os.Exit(1)
	}
	buf.WriteString("}\n")

	if err := os.WriteFile(os.Args[1], buf.Bytes(), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// writeIndented renders a style's CSS into the buffer, indented one level so the
// media-query block stays readable.
func writeIndented(buf *bytes.Buffer, formatter *html.Formatter, style *chroma.Style) error {
	var inner bytes.Buffer
	if err := formatter.WriteCSS(&inner, style); err != nil {
		return err
	}
	for _, line := range bytes.Split(bytes.TrimRight(inner.Bytes(), "\n"), []byte("\n")) {
		buf.WriteString("  ")
		buf.Write(line)
		buf.WriteByte('\n')
	}
	return nil
}
