// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package awaitserver

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Node interface {
	IsNode()
	GetID() string
}

// An object that can be forced. For awaitables, sync blocks until the fact exists.
type Syncer interface {
	IsNode()
	IsSyncer()
	GetID() string
	GetSync() string
}

type Query struct {
}

type AwaitMode string

const (
	// The first awaitable to finish wins, failure included (failure raises).
	AwaitModeFirstSettled AwaitMode = "FIRST_SETTLED"
	// Failures are skipped; raises only when every awaitable failed.
	AwaitModeFirstSuccess AwaitMode = "FIRST_SUCCESS"
)

var AllAwaitMode = []AwaitMode{
	AwaitModeFirstSettled,
	AwaitModeFirstSuccess,
}

func (e AwaitMode) IsValid() bool {
	switch e {
	case AwaitModeFirstSettled, AwaitModeFirstSuccess:
		return true
	}
	return false
}

func (e AwaitMode) String() string {
	return string(e)
}

func (e *AwaitMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AwaitMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AwaitMode", str)
	}
	return nil
}

func (e AwaitMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AwaitMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AwaitMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MailboxEventKind string

const (
	MailboxEventKindMessage MailboxEventKind = "MESSAGE"
	MailboxEventKindTick    MailboxEventKind = "TICK"
)

var AllMailboxEventKind = []MailboxEventKind{
	MailboxEventKindMessage,
	MailboxEventKindTick,
}

func (e MailboxEventKind) IsValid() bool {
	switch e {
	case MailboxEventKindMessage, MailboxEventKindTick:
		return true
	}
	return false
}

func (e MailboxEventKind) String() string {
	return string(e)
}

func (e *MailboxEventKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MailboxEventKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MailboxEventKind", str)
	}
	return nil
}

func (e MailboxEventKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MailboxEventKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MailboxEventKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
