// genthemes generates the per-scheme CSS under css/base16/ from the
// tinted-theming/schemes submodule (schemes/). Each scheme becomes a
// stylesheet defining the --base00..--base0F variables that syntax.css and
// page.tmpl color the whole site through; the file naming matches what
// switcher.js expects (base16-<name>.css), so scheme names double as the
// values persisted in readers' localStorage.
//
// base24 schemes are a strict superset of base16 (base00-base0F keep the
// same semantics; base10-base17 add brighter terminal variants the site
// never uses), so they are mapped down by taking just the base16 slots.
// When the same name exists in both systems the base16 version wins.
package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var (
	slotRe = regexp.MustCompile(`(?m)^\s*base(0[0-9A-Fa-f]):\s*"?#?([0-9a-fA-F]{6}|[0-9a-fA-F]{3})"?`)
	nameRe = regexp.MustCompile(`(?m)^(?:name|scheme):\s*"(.+)"`)
	authRe = regexp.MustCompile(`(?m)^author:\s*"(.+)"`)
)

type scheme struct {
	name, displayName, author, source string
	slots                             map[string]string // "00".."0F" -> 6-digit hex
}

func parseScheme(path string) (*scheme, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	s := &scheme{
		name:   strings.TrimSuffix(filepath.Base(path), ".yaml"),
		source: path,
		slots:  map[string]string{},
	}
	for _, m := range slotRe.FindAllStringSubmatch(string(data), -1) {
		hex := m[2]
		if len(hex) == 3 {
			hex = string([]byte{hex[0], hex[0], hex[1], hex[1], hex[2], hex[2]})
		}
		s.slots[strings.ToUpper(m[1])] = strings.ToLower(hex)
	}
	if len(s.slots) != 16 {
		return nil, fmt.Errorf("%s: found %d of 16 base16 slots", path, len(s.slots))
	}
	if m := nameRe.FindStringSubmatch(string(data)); m != nil {
		s.displayName = m[1]
	}
	if m := authRe.FindStringSubmatch(string(data)); m != nil {
		s.author = m[1]
	}
	return s, nil
}

func (s *scheme) css() string {
	var b strings.Builder
	header := s.displayName
	if s.author != "" {
		header += " by " + s.author
	}
	fmt.Fprintf(&b, "/* %s — generated by cmd/genthemes from %s */\n\n:root {\n", header, s.source)
	var keys []string
	for k := range s.slots {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(&b, "  --base%s: #%s;\n", k, s.slots[k])
	}
	b.WriteString("}\n")
	return b.String()
}

func main() {
	schemes := map[string]*scheme{}
	// base16 last so it wins name collisions with base24
	for _, system := range []string{"base24", "base16"} {
		paths, err := filepath.Glob(filepath.Join("schemes", system, "*.yaml"))
		if err != nil || len(paths) == 0 {
			log.Fatalf("no %s schemes found; is the docs/schemes submodule initialized?", system)
		}
		for _, p := range paths {
			s, err := parseScheme(p)
			if err != nil {
				log.Fatal(err)
			}
			schemes[s.name] = s
		}
	}

	outDir := filepath.Join("css", "base16")
	if err := os.RemoveAll(outDir); err != nil {
		log.Fatal(err)
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		log.Fatal(err)
	}
	for name, s := range schemes {
		out := filepath.Join(outDir, "base16-"+name+".css")
		if err := os.WriteFile(out, []byte(s.css()), 0o644); err != nil {
			log.Fatal(err)
		}
	}
	log.Printf("generated %d schemes into %s", len(schemes), outDir)
}
