id = "bind"
name = "Bind"
version = "0.1.1"
schema_version = 1
description = "Bind language support for Zed - a functional language for Dagger with Hindley-Milner type inference"
authors = ["vito"]
repository = "https://github.com/vito/bind"

[grammars.bind]
repository = "https://github.com/vito/bind"
commit = "3ddf4f105b994f3323231ee4adb20db4d10b1edb"
path = "treesitter"
