id = "bind"
name = "Bind"
version = "0.1.1"
schema_version = 1
description = "Bind language support for Zed"
authors = ["vito"]
repository = "https://github.com/vito/bind"

[grammars.bind]
repository = "https://github.com/vito/bind"
commit = "82bd50f183220628c0e896ec0757573ad957ad8e"
path = "treesitter"
